### ISSUE TITLE
Failed to run unmodified

### ISSUE THREAD

**Issue by ixaxaar** [jaceklaskowski/spark-activator#5]
Did an `activator new`

select `spark-streaming-scala-akka`

run `./activator clean run`

This is the output:

```
[info] Set current project to test (in build file:/home/ixaxaar/src/cerebro/spark-jobs/test/)
[success] Total time: 0 s, completed 9 May, 2016 4:45:51 PM
[info] Updating {file:/home/ixaxaar/src/cerebro/spark-jobs/test/}test...
[info] Resolving org.scala-lang#scala-library;2.11.7 ...
[info] Formatting 1 Scala source {file:/home/ixaxaar/src/cerebro/spark-jobs/test/}test(compile) ...
[info] Resolving org.apache.spark#spark-streaming_2.11;1.5.2 ...
[warn]  module not found: org.apache.spark#spark-streaming_2.11;1.5.2
[info] Resolving org.apache.hadoop#hadoop-client;2.7.1 ...
[warn]  module not found: org.apache.hadoop#hadoop-client;2.7.1
[info] Resolving org.scalatest#scalatest_2.11;2.2.5 ...
[warn]  module not found: org.scalatest#scalatest_2.11;2.2.5
[info] Resolving org.mockito#mockito-all;1.10.19 ...
[warn]  module not found: org.mockito#mockito-all;1.10.19
[info] Resolving jline#jline;2.12.1 ...
[warn]  [FAILED     ] org.scala-lang#scala-library;2.11.7!scala-library.jar:  (0ms)
[warn]  [FAILED     ] com.typesafe.akka#akka-actor_2.11;2.4.1!akka-actor_2.11.jar:  (0ms)
[warn]  [FAILED     ] com.typesafe.akka#akka-testkit_2.11;2.4.1!akka-testkit_2.11.jar:  (0ms)
[warn]  [FAILED     ] com.typesafe#config;1.3.0!config.jar(bundle):  (0ms)
[warn]  [FAILED     ] ch.qos.logback#logback-classic;1.1.3!logback-classic.jar:  (0ms)
[warn]  [FAILED     ] ch.qos.logback#logback-core;1.1.3!logback-core.jar:  (0ms)
[warn]  [FAILED     ] org.slf4j#slf4j-api;1.7.7!slf4j-api.jar:  (0ms)
[warn]  [FAILED     ] org.scala-lang#scala-compiler;2.11.7!scala-compiler.jar:  (0ms)
[warn]  [FAILED     ] org.scala-lang#scala-reflect;2.11.7!scala-reflect.jar:  (0ms)
[warn]  [FAILED     ] org.scala-lang.modules#scala-xml_2.11;1.0.4!scala-xml_2.11.jar(bundle):  (0ms)
[warn]  [FAILED     ] org.scala-lang.modules#scala-parser-combinators_2.11;1.0.4!scala-parser-combinators_2.11.jar(bundle):  (0ms)
[warn]  [FAILED     ] jline#jline;2.12.1!jline.jar:  (0ms)
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.apache.spark#spark-streaming_2.11;1.5.2: not found
[warn]  :: org.apache.hadoop#hadoop-client;2.7.1: not found
[warn]  :: org.scalatest#scalatest_2.11;2.2.5: not found
[warn]  :: org.mockito#mockito-all;1.10.19: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::              FAILED DOWNLOADS            ::
[warn]  :: ^ see resolution messages for details  ^ ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-lang#scala-library;2.11.7!scala-library.jar
[warn]  :: com.typesafe.akka#akka-actor_2.11;2.4.1!akka-actor_2.11.jar
[warn]  :: com.typesafe#config;1.3.0!config.jar(bundle)
[warn]  :: com.typesafe.akka#akka-testkit_2.11;2.4.1!akka-testkit_2.11.jar
[warn]  :: ch.qos.logback#logback-classic;1.1.3!logback-classic.jar
[warn]  :: ch.qos.logback#logback-core;1.1.3!logback-core.jar
[warn]  :: org.slf4j#slf4j-api;1.7.7!slf4j-api.jar
[warn]  :: org.scala-lang#scala-compiler;2.11.7!scala-compiler.jar
[warn]  :: org.scala-lang#scala-reflect;2.11.7!scala-reflect.jar
[warn]  :: org.scala-lang.modules#scala-xml_2.11;1.0.4!scala-xml_2.11.jar(bundle)
[warn]  :: org.scala-lang.modules#scala-parser-combinators_2.11;1.0.4!scala-parser-combinators_2.11.jar(bundle)
[warn]  :: jline#jline;2.12.1!jline.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]      org.apache.spark:spark-streaming_2.11:1.5.2 (/home/ixaxaar/src/cerebro/spark-jobs/test/build.sbt#L9-10)
[warn]        +- pl.japila:test_2.11:1.0
[warn]      org.apache.hadoop:hadoop-client:2.7.1 (/home/ixaxaar/src/cerebro/spark-jobs/test/build.sbt#L9-10)
[warn]        +- pl.japila:test_2.11:1.0
[warn]      org.scalatest:scalatest_2.11:2.2.5 (/home/ixaxaar/src/cerebro/spark-jobs/test/build.sbt#L9-10)
[warn]        +- pl.japila:test_2.11:1.0
[warn]      org.mockito:mockito-all:1.10.19 (/home/ixaxaar/src/cerebro/spark-jobs/test/build.sbt#L9-10)
[warn]        +- pl.japila:test_2.11:1.0
sbt.ResolveException: unresolved dependency: org.apache.spark#spark-streaming_2.11;1.5.2: not found
unresolved dependency: org.apache.hadoop#hadoop-client;2.7.1: not found
download failed: org.scala-lang#scala-library;2.11.7!scala-library.jar
download failed: com.typesafe.akka#akka-actor_2.11;2.4.1!akka-actor_2.11.jar
download failed: com.typesafe#config;1.3.0!config.jar(bundle)
download failed: com.typesafe.akka#akka-testkit_2.11;2.4.1!akka-testkit_2.11.jar
unresolved dependency: org.scalatest#scalatest_2.11;2.2.5: not found
unresolved dependency: org.mockito#mockito-all;1.10.19: not found
download failed: ch.qos.logback#logback-classic;1.1.3!logback-classic.jar
download failed: ch.qos.logback#logback-core;1.1.3!logback-core.jar
download failed: org.slf4j#slf4j-api;1.7.7!slf4j-api.jar
download failed: org.scala-lang#scala-compiler;2.11.7!scala-compiler.jar
download failed: org.scala-lang#scala-reflect;2.11.7!scala-reflect.jar
download failed: org.scala-lang.modules#scala-xml_2.11;1.0.4!scala-xml_2.11.jar(bundle)
download failed: org.scala-lang.modules#scala-parser-combinators_2.11;1.0.4!scala-parser-combinators_2.11.jar(bundle)
download failed: jline#jline;2.12.1!jline.jar
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:294)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
    at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
    at xsbt.boot.Using$.withResource(Using.scala:10)
    at xsbt.boot.Using$.apply(Using.scala:9)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
    at sbt.IvySbt.withIvy(Ivy.scala:127)
    at sbt.IvySbt.withIvy(Ivy.scala:124)
    at sbt.IvySbt$Module.withModule(Ivy.scala:155)
    at sbt.IvyActions$.updateEither(IvyActions.scala:168)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1392)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1388)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1422)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1420)
    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1425)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1419)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
    at sbt.Classpaths$.cachedUpdate(Defaults.scala:1442)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1371)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1325)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.apache.spark#spark-streaming_2.11;1.5.2: not found
[error] unresolved dependency: org.apache.hadoop#hadoop-client;2.7.1: not found
[error] download failed: org.scala-lang#scala-library;2.11.7!scala-library.jar
[error] download failed: com.typesafe.akka#akka-actor_2.11;2.4.1!akka-actor_2.11.jar
[error] download failed: com.typesafe#config;1.3.0!config.jar(bundle)
[error] download failed: com.typesafe.akka#akka-testkit_2.11;2.4.1!akka-testkit_2.11.jar
[error] unresolved dependency: org.scalatest#scalatest_2.11;2.2.5: not found
[error] unresolved dependency: org.mockito#mockito-all;1.10.19: not found
[error] download failed: ch.qos.logback#logback-classic;1.1.3!logback-classic.jar
[error] download failed: ch.qos.logback#logback-core;1.1.3!logback-core.jar
[error] download failed: org.slf4j#slf4j-api;1.7.7!slf4j-api.jar
[error] download failed: org.scala-lang#scala-compiler;2.11.7!scala-compiler.jar
[error] download failed: org.scala-lang#scala-reflect;2.11.7!scala-reflect.jar
[error] download failed: org.scala-lang.modules#scala-xml_2.11;1.0.4!scala-xml_2.11.jar(bundle)
[error] download failed: org.scala-lang.modules#scala-parser-combinators_2.11;1.0.4!scala-parser-combinators_2.11.jar(bundle)
[error] download failed: jline#jline;2.12.1!jline.jar
```

**Comment by ixaxaar** [comment]
Never mind, was an sbt issue. Deleted `~/.sbt` and it worked.
